build:
  variables:
    GIT_CLEAN_FLAGS: none
  stage: build
  only:
    - tags
  artifacts:
    paths:
      - ./
    exclude:
      - .git
      - .git/**/*
  script:
    - npm i --no-audit
    - npm run build
publish:
  variables:
    GIT_STRATEGY: none
  stage: deploy
  only:
    - tags
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish